moviesduck_project/home/urls.py
from django.urls import path
from home import views 

app_name = 'home'
urlpatterns = [
    path ('',views.Home.as_view(),name= 'home'),
    path('about/', views.about.as_view(), name='about'),

]

moviesduck_project/moviesduck_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('', include('home.urls', namespace='home')),
    path('movies/', include('movies.urls', namespace='movies')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('registration.urls', namespace='registration')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
  from django.conf.urls.static import static
  urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

moviesduck_project/registration/urls.py
from django.urls import path
from . import views

app_name = 'registration'
urlpatterns = [
  path('signup/', views.Signup.as_view(), name='signup'),
  path('me/', views.ProfileUpdate.as_view(), name='profile'),
  path('settings/', views.AccountUpdate.as_view(), name='account'),
  # path('name_change/', views.NameUpdate.as_view(), name='name-change'),
]

moviesduck_project/templates/includes/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item {% if request.resolver_match.view_name == 'home:home' %}active{% endif %}">
          <a class="nav-link" href="{% url 'home:home' %}">
            <i class="fas fa-fw fa-home"></i>
            Home
          </a>
        </li>
        {% if user.is_authenticated %}
          <li class="nav-item {% if request.resolver_match.view_name == 'movies:movie_list' %}active{% endif %}">
            <a class="nav-link" href="{% url 'movies:movie_list' %}">
              <i class="fas fa-fw fa-ticket-alt"></i>
              Movies
            </a>
          </li>
        {% endif %}
        <li class="nav-item {% if request.resolver_match.view_name == 'home:about' %}active{% endif %}">
          <a class="nav-link" href="{% url 'home:about' %}">
            <i class="fas fa-fw fa-address-card"></i>
            About
          </a>
        </li>
      </ul>
      {% if user.is_authenticated %}
        <ul class="navbar-nav">
          <!-- Nav Item - User Information -->
          <li class="nav-item dropdown no-arrow">
            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <span class="mr-2 d-none d-lg-inline text-white small font-weight-bolder">{{ user.username }}</span>
              <img
                class="img-profile rounded-circle"
                width="32px"
                src="{{ user.profile.avatar.url }}"
                alt="{{ user.username }}">
            </a>
            <!-- Dropdown - User Information -->
            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
              <a class="dropdown-item text-secondary" href="{% url 'registration:profile' %}">
                <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                Profile
              </a>
              <a class="dropdown-item text-secondary" href="{% url 'registration:account' %}">
                <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                Account settings
              </a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item text-secondary" href="{% url 'logout' %}">
                <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                Logout
              </a>
            </div>
          </li>
        </ul>
      {% else %}
        <ul class="navbar-nav">
          <li class="nav-item {% if request.resolver_match.view_name == 'login' %}active{% endif %}">
            <a class="nav-link" href="{% url 'login' %}">Login</a>
          </li>
          <li class="nav-item {% if request.resolver_match.view_name == 'registration:signup' %}active{% endif %}">
            <a class="nav-link" href="{% url 'registration:signup' %}">Signup</a>
          </li>
        </ul>
      {% endif %}
    </div>
  </div>
</nav>

moviesduck_project/templates/includes/sidebar.html
{% load static %}
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

  <!-- Sidebar - Brand -->
  <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{% url 'home:home' %}">
    <div class="sidebar-brand-icon">
      <!-- <i class="fas fa-laugh-wink"></i> -->
      <img width="32px" src="{% static 'img/duck.png' %}" alt="logo">
    </div>
    <div class="sidebar-brand-text mx-3">MovieDuck</div>
  </a>

  <!-- Divider -->
  <hr class="sidebar-divider my-0">

  <!-- Nav Item - Dashboard -->
  <li class="nav-item {% if request.resolver_match.view_name == 'movies:movie_list' %}active{% endif %}">
    <a class="nav-link" href="{% url 'movies:movie_list' %}">
      <i class="fas fa-fw fa-ticket-alt"></i>
      <span>Movies</span></a>
  </li>

  <!-- Divider -->
  <hr class="sidebar-divider">

  <!-- Nav Item - Pages Collapse Menu -->
  
  <li class="nav-item {% if request.resolver_match.view_name == 'registration:profile' %}active{% endif %}">
    <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePages" aria-expanded="true" aria-controls="collapsePages">
      <i class="fas fa-fw fa-user"></i>
      <span>User</span>
    </a>
    <div id="collapsePages" class="collapse" aria-labelledby="headingPages" data-parent="#accordionSidebar">
      <div class="bg-white py-2 collapse-inner rounded">
        <a class="collapse-item" href="{% url 'registration:profile' %}">Profile</a>
        <a class="collapse-item" href="{% url 'registration:account' %}">Account settings</a>
        <div class="collapse-divider"></div>
        <a class="collapse-item" href="{% url 'logout' %}">Logout</a>
      </div>
    </div>
  </li>

  <!-- Nav Item - Tables -->
  <li class="nav-item {% if request.resolver_match.view_name == 'home:about' %}active{% endif %}">
    <a class="nav-link" href="{% url 'home:about' %}">
      <i class="fas fa-fw fa-address-card"></i>
      <span>About</span></a>
  </li>

  <!-- Divider -->
  <hr class="sidebar-divider d-none d-md-block">

  <!-- Sidebar Toggler (Sidebar) -->
  <div class="text-center d-none d-md-inline">
    <button class="rounded-circle border-0" id="sidebarToggle"></button>
  </div>

</ul>