moviesduck_project/home/urls.py
from django.urls import path
from home import views 

app_name = 'home'
urlpatterns = [
    path ('',views.Home.as_view(),name= 'home'),
    path('about/', views.about.as_view(), name='about'),

]

moviesduck_project/movies/urls.py
from django.urls import path
from movies import views
from django.views.generic import TemplateView # temporal import

app_name = "movies"
urlpatterns = [
    # Carousel-based lists
    path( # Newest movies
        "newest/carousel/",
        views.CarouselNewReleases.as_view(),
        name="newest_carousel"
        ),
    path( # Trending (most reviews in last 24 hours)
        "trending/carousel/",
        views.CarouselTrending.as_view(),
        name="trending_carousel"
        ),
    path( # Newest reviews
        "newreviews/carousel/",
        views.CarouselRecentReviews.as_view(),
        name="newreviews_carousel"
        ),
    path(
        "",
        views.MovieList.as_view(),
        name="movie_list"
        ),
    # Movie details page
    path( # Normal movie details page
        "<int:pk>/",
        views.MovieDetail.as_view(),
        name="movie_detail"
        ),
    # Review interaction
    path( # Review details page
        "<int:movie_pk>/reviews/<int:pk>",
        views.ReviewDetail.as_view(),
        name="review_detail"
        ),
    path( # Create a review
        "<int:movie_pk>/reviews/create",
        views.CreateReview.as_view(),
        name="review_create"
        ),
    path( # Delete a review
        "<int:movie_pk>/reviews/<int:pk>/delete",
        views.DeleteReview.as_view(),
        name="review_delete"
        ),
    path( # Toggle like/unlike on a review
        "reviews/<int:pk>/like",
        views.toggle_like_review,
        name="review_like"
        ),
    path( # Respond to a review
        "<int:movie_pk>/reviews/<int:review_pk>/respond",
        views.RespondToReview.as_view(),
        name="review_respond"
        ),
    # Comment interaction
    path( # Toggle like/unlike on a comment
        "comments/<int:pk>/like",
        views.toggle_like_comment,
        name="comment_like"
        ),
    path( # Delete a comment
        "<int:movie_pk>/reviews/<int:review_pk>/comments/<int:pk>/delete",
        views.DeleteComment.as_view(),
        name="comment_delete"
        ),
    path( # Respond to a comment
        "<int:movie_pk>/reviews/<int:review_pk>/comments/<int:comment_pk>/respond",
        views.RespondToComment.as_view(),
        name="comment_respond"
        ),
]

moviesduck_project/moviesduck_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('', include('home.urls', namespace='home')),
    path('movies/', include('movies.urls', namespace='movies')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('registration.urls', namespace='registration')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
  from django.conf.urls.static import static
  urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

moviesduck_project/registration/urls.py
from django.urls import path
from . import views

app_name = 'registration'
urlpatterns = [
  path('signup/', views.Signup.as_view(), name='signup'),
  path('me/', views.ProfileUpdate.as_view(), name='profile'),
  path('settings/', views.AccountUpdate.as_view(), name='account'),
  # path('name_change/', views.NameUpdate.as_view(), name='name-change'),
]

moviesduck_project/home/models.py
from django.db import models

# Create your models here.

moviesduck_project/home/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.
# Se creo la vista de home

class Home(LoginRequiredMixin, TemplateView):
    template_name = 'home/home.html'

class about (TemplateView):
    template_name = 'home/about.html'

moviesduck_project/templates/home/about.html
{% extends 'base.html' %}
{% load static %}

{% block title %}About MovieDuck{%endblock %}

{% block content %}
  <div class="row m-5">
    <div class="col-12 col-lg-8">
      <h3 class="text-primary text-uppercase font-weight-bolder">
        Welcome to MovieDuck
      </h3>
      <div class="media mt-5">
        <img src="{% static 'img/duck.png' %}" alt="The Movieduck logo." class="mr-5 d-none d-lg-block">
        <div class="media-body text-white align-middle">
          <img height="150px" src="{% static 'img/duck.png' %}" alt="The Movieduck logo." class="mr-5 d-block d-lg-none float-left">
          <h1 class="display-4 font-italic">"All reviews. No quackery."</h1>
          <h4 class="mt-4">Here at MovieDuck we don't have complicated gimmicks, obtuse scores, or unfair scales.</h4>
          <h4 class="mt-4">Just share your thoughts, your score, and let people see your review.</h4>
          <h4 class="mt-4 font-italic font-weight-light text-muted">Tomatoes are for throwing at the screen!</h4>
        </div>
      </div>
      <!--
      <div class="row">
        <div class="col-2">
          <img width="64px" src="{% static 'img/duck.png' %}" alt="logo">
        </div>
        <div class="col-10">
          <h2 class="text-white mt-4">
            All reviews. No quackery.
          </h2>
        </div>
      </div>
      -->
      {% if not user.is_authenticated %}
        <a class="btn btn-primary btn-lg mt-5" href="{% url 'registration:signup' %}">
          <i class="fa fa-fw fa-users"></i>
          Sign up!
        </a>
      {% else %}
        <a class="btn btn-primary btn-lg mt-5" href="{% url 'home:home' %}">
          <i class="fa fa-fw fa-home"></i>
          Go to Home
        </a>
      {% endif %}
      <br />
      <a class="btn btn-secondary mt-4" href="https://github.com/LuisManuelGlz/MovieDuck" target="_blank" rel="noopener noreferrer">
        <i class="fab fa-fw fa-github"></i>
        Source Code
      </a>
    </div>
  </div>
{% endblock %}

moviesduck_project/templates/home/home.html
{% extends 'base.html'%}

{%block title%}home{%endblock%}

{% block content %}

<h2>Movie Duck</h2>

<!--########## MOVIE LISTS ##########-->
<style>
.carousel img.d-block { max-height: 500px; min-width: auto; object-fit: cover; }
</style>
<h1>Trending</h1>
<div id="trendingCarousel" class="carousel slide mb-5" data-ride="carousel">
	<div class="carousel-inner rounded-lg"></div>
</div>

<h1>New Releases</h1>
<div id="newReleasesCarousel" class="carousel slide mb-5" data-ride="carousel">
	<div class="carousel-inner rounded-lg"></div>
</div>

<h1>Recent Reviews</h1>
<div id="newReviewsCarousel" class="carousel slide mb-5" data-ride="carousel">
	<div class="carousel-inner rounded-lg"></div>
</div>
{%endblock%}
{% block js-extras %}<script type="text/javascript">
	$("#trendingCarousel .carousel-inner").load("{% url 'movies:trending_carousel' %}");
	$("#newReleasesCarousel .carousel-inner").load("{% url 'movies:newest_carousel' %}");
	$("#newReviewsCarousel .carousel-inner").load("{% url 'movies:newreviews_carousel' %}");
	</script>{% endblock js-extras %}